### ISSUE TITLE
Save Spotify playlist and thumbnail

### ISSUE THREAD

**Issue by flamedfury** [katydecorah/spotify-to-yaml-action#118]
The action ran as scheduled (yay).

See: https://github.com/flamedfury/metadata-library/actions/runs/4463788562/jobs/7839333646

```bash
Run katydecorah/spotify-to-yaml-action@v7.2.0
(node:1320) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Error: Error: TypeError: currentJson is not iterable
```

What json file is it referring to here?

**Comment by katydecorah** [comment]
It might be having trouble loading the initial yml file to json if it's blank. 

I thought I had fixed this, but in the meantime, you could try updating your data file with a temporary value like:

```yaml
- playlist: Test
```

**Comment by flamedfury** [comment]
Fantastic, that worked :)
