### ISSUE TITLE
Forking to use in the sourthern hemisphere

### ISSUE THREAD

**Issue by flamedfury** [katydecorah/spotify-to-yaml-action#95]
Hello again,

I'm going to fork this and have a go at modifying it to work with the seasons in the southern hemisphere.

```
  const season = {
    2: "Summer",
    5: "Autumn",
    8: "Winter",
    11: "Spring",
  };
``` 

Before I begin, are you aware of a simple method for me to go about this? Otherwise, I'm going to dive in and hack away until it works :)

~fLaMEd.

**Comment by katydecorah** [comment]
@flamedfury Love this. If you fork then you can update that `season` object as you want! 

We can definitely make this change in this repository by creating a new action input. This new `input` in `action.yml` could be `seasonNames` with `default: 'Winter,Spring,Summer,Fall'`. This will allow anyone one to use the default automatically or specify their preferred seasonal names and/or order.

Then in `learn-playlist-name.ts`. We can do something like `const seasonNames = getInput("season-names").split(",");` to create an array from the action input and then update the hardcoded seasons names with something like:

```jso
const season = {
    2: seasonNames[0],
    5: seasonNames[1],
    8: seasonNames[2],
    11: seasonNames[3],
  };
```

**Comment by flamedfury** [comment]
Hello. Your second solution sounds cleaner to me. It will also save me a lot of time as I've not got an idea where to start outside of your hints.

**Comment by katydecorah** [comment]
@flamedfury All set! I also updated https://github.com/katydecorah/seasonal-post-action with the same action input (in case you also use that!). Let me know if you find any bugs!

**Comment by flamedfury** [comment]
Hi, I'm unsure whether to raise a new issue each time or continue to use this one as it relates.

I've updated my action to reflect the latest changes (thanks for the quick turn around).

What I've done.

Created 3x public playlists:
- 2022 Autumn
- 2022 Winter
- 2022 Spring
- 2022/2023 Summer

Set my seasonNames:
```yaml
with:
    seasonNames: Summer,Autumn,Winter,Spring
```
I have [run the action](https://github.com/flamedfury/metadata-library/actions/runs/4038878316) and get the following error:

```
Run katydecorah/spotify-to-yaml-action@v7.2.0
(node:1303) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Error: Could not find playlist "2023 undefined". Is it private?
Error: Cannot read properties of undefined (reading 'formatted_name')
```

**Comment by flamedfury** [comment]
I'll be looking at tying this all together with [seasonal-post-action](https://github.com/katydecorah/seasonal-post-action) soon. Hopefully, this weekend.

I anticipate a lot of thought about how it will all fit together. The challenge is to create the post files in my 11ty project repo...

**Comment by katydecorah** [comment]
@flamedfury I think it's failing because the current month (January) does not mark and end of season. I should update the code to throw a better error message and fail sooner.
